### ISSUE TITLE
Remove /var/lib/jelastic/keys/bannedip.txt from removeIP action

### ISSUE THREAD

**Issue by rauladorean** [jelastic-jps/fail2ban#10]
https://github.com/jelastic-jps/fail2ban/blob/86092b115fcf0b65e9dcc185c69511b15d883a47/manifest.jps#L88 was added in d10ca9238ece60f45a6c4ef780a3a9ddc145282e but it doesn't appear to be used.

Any idea why it was added in the first place? Can we have it removed?

**Comment by lazarenkoalexey** [comment]
Hi @rauladorean,
The file _bannedip.txt_ content [is used](https://github.com/jelastic-jps/fail2ban/blob/master/manifest.jps#L89) while adding manually a new IP address to a Banned IP list via [settings form](https://github.com/jelastic-jps/fail2ban/blob/master/manifest.jps#L16) or after redeployContainer action
