### ISSUE TITLE
NGINX load balancer version 1.26.0-almalinux-9 throws an error while installing this addon.

### ISSUE THREAD

**Issue by joostvannus** [jelastic-jps/fail2ban#11]
With the latest load balancer node version for nginx, 1.26.0-almalinux-9, we get the following error:
Job for fail2ban.service failed because the service did not take the steps required by its unit configuration.

**Comment by dimkadt** [comment]
Thanks for reporting, task was created for a fix (ticket id - JE-71820).

**Comment by joostvannus** [comment]
It seems that the issue has been fixed. I will close this issue.
